# Generated by Django 5.0.6 on 2024-07-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justify', '0002_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
